os: linux
group: stable
dist: trusty
sudo: required
language: php
php: 7.2

branches:
  only: master

before_script:
  - mkdir -p build/logs
  - composer install --no-interaction
  - composer require codeclimate/php-test-reporter:dev-master --no-interaction

script:
  - vendor/bin/phpunit tests

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa

notifications:
  email: "bianco@javanile.org"